name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git*'
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      needs: build
      with:
        artifacts: "release.zip"
